### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [metricalp/react#1]
Dear @metricalp team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by MetinArslanturk** [comment]
Hey hi,

Good point. It was a silly mistake to run this account as a personal account. Now, I converted it to an organisation.

Thanks

**Comment by Neustradamus** [comment]
Dear @metricalp team, @MetinArslanturk: Thanks a lot for your quick change :)

Do not forget to add personal accounts in public in people place:
- https://github.com/orgs/metricalp/people
